param(
  [string]$SourceDir = "backend/models_artifacts/reports",
  [string]$TargetDir = "raport/figures/model",
  [string]$MetricsOut = "raport/sections/generated_metrics.tex"
)

Set-StrictMode -Version Latest
$ErrorActionPreference = "Stop"

if (-not (Test-Path $SourceDir)) {
  throw "Nie znaleziono katalogu z raportami modelu: $SourceDir"
}

New-Item -ItemType Directory -Force $TargetDir | Out-Null

$latestTraining = Get-ChildItem $SourceDir -Filter "training_report_*.json" |
  Sort-Object LastWriteTime -Descending |
  Select-Object -First 1

if (-not $latestTraining) {
  throw "Brak pliku training_report_*.json w $SourceDir"
}

$timestamp = [regex]::Match($latestTraining.Name, "training_report_(.+)\.json").Groups[1].Value
if (-not $timestamp) {
  throw "Nie udało się odczytać timestamp z $($latestTraining.Name)"
}

$filesToCopy = @(
  "training_report_$timestamp.json",
  "confusion_matrix_$timestamp.png",
  "roc_$timestamp.png",
  "decision_tree_$timestamp.png",
  "decision_tree_feature_importance_$timestamp.png",
  "decision_tree_rules_$timestamp.txt",
  "evaluation_report.json",
  "eval_confusion_matrix.png",
  "eval_roc.png"
)

foreach ($file in $filesToCopy) {
  $src = Join-Path $SourceDir $file
  if (Test-Path $src) {
    Copy-Item $src $TargetDir -Force
  }
}

$train = Get-Content (Join-Path $SourceDir "training_report_$timestamp.json") -Raw | ConvertFrom-Json
$evalPath = Join-Path $SourceDir "evaluation_report.json"
$eval = $null
if (Test-Path $evalPath) {
  $eval = Get-Content $evalPath -Raw | ConvertFrom-Json
}

function Format-Num([double]$Value, [int]$Digits = 4) {
  $culture = [System.Globalization.CultureInfo]::InvariantCulture
  return $Value.ToString("F$Digits", $culture)
}

$tm = $train.metrics
$em = $eval.metrics

$tex = @"
% Auto-generated by raport/scripts/refresh_model_assets.ps1
% Source timestamp: $timestamp

\subsubsection{Metryki z treningu (hold-out, GroupShuffleSplit)}
\begin{table}[H]
  \centering
  \begin{tabular}{l c}
    \toprule
    Metryka & Wartosc \\
    \midrule
    Precision & $(Format-Num $tm.precision) \\
    Recall & $(Format-Num $tm.recall) \\
    F1-score & $(Format-Num $tm.f1) \\
    ROC-AUC & $(Format-Num $tm.roc_auc) \\
    False Positive Rate (human) & $(Format-Num $tm.false_positive_rate_human) \\
    \bottomrule
  \end{tabular}
  \caption{Metryki modelu na zbiorze testowym podczas treningu}
  \label{tab:train-metrics}
\end{table}

\begin{table}[H]
  \centering
  \begin{tabular}{l c}
    \toprule
    Element & Wartosc \\
    \midrule
    TN & $($tm.confusion_matrix.tn) \\
    FP & $($tm.confusion_matrix.fp) \\
    FN & $($tm.confusion_matrix.fn) \\
    TP & $($tm.confusion_matrix.tp) \\
    \bottomrule
  \end{tabular}
  \caption{Confusion matrix (trening)}
  \label{tab:train-cm}
\end{table}

"@

if ($eval) {
  $delay = $eval.detection_delay
  $avgDelay = if ($delay.avg_events_to_detect) { Format-Num ([double]$delay.avg_events_to_detect) } else { "N/A" }
  $medianDelay = if ($delay.median_events_to_detect) { Format-Num ([double]$delay.median_events_to_detect) } else { "N/A" }

  $tex += @"
\subsubsection{Metryki ewaluacyjne (aktywny model)}
\begin{table}[H]
  \centering
  \begin{tabular}{l c}
    \toprule
    Metryka & Wartosc \\
    \midrule
    Precision & $(Format-Num $em.precision) \\
    Recall & $(Format-Num $em.recall) \\
    F1-score & $(Format-Num $em.f1) \\
    ROC-AUC & $(Format-Num $em.roc_auc) \\
    False Positive Rate (human) & $(Format-Num $em.false_positive_rate_human) \\
    \bottomrule
  \end{tabular}
  \caption{Metryki z raportu ewaluacyjnego}
  \label{tab:eval-metrics}
\end{table}

\begin{table}[H]
  \centering
  \begin{tabular}{l c}
    \toprule
    Wskaznik & Wartosc \\
    \midrule
    Liczba probek & $($eval.samples) \\
    Liczba sesji & $($eval.sessions) \\
    Avg events to detect bot & $avgDelay \\
    Median events to detect bot & $medianDelay \\
    Detection delay count & $($delay.count) \\
    Unseen bot recall count & $($eval.unseen_bot_recall.count) \\
    \bottomrule
  \end{tabular}
  \caption{Statystyki operacyjne ewaluacji}
  \label{tab:eval-operational}
\end{table}
"@
}

Set-Content -Path $MetricsOut -Value $tex -Encoding UTF8

Write-Host "Zaktualizowano artefakty modelu i metryki."
Write-Host "Timestamp treningu: $timestamp"
